# Generated by Django 4.0.6 on 2022-08-06 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_category_product_isactive'),
        ('myapp', '0004_alter_product_slug'),
    ]

    operations = [
    ]
